### ISSUE TITLE
Error when cmake is running

### ISSUE THREAD

**Issue by rcalxrc08** [lgpasquale/kandinsky#1]
Hi, 
i would like to use and test the performances of your library but i have some problem with the "cupido" installation.
I am running you lib on Mint 18.1 serena, i have cmake 3.7.2.
when i run the CMake i get the following:
`cmake ..
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading cupid...
Error renaming from "cupid-aff23ed14632c33ab6e60bb26ff686f1cc9b3838" to "cupid": No such file or directory
CMake Error at CMakeLists.txt:36 (include):
  include could not find load file:

    ***/kandinsky/build1/cupid/src/SetUpProject.cmake

CMake Error at CMakeLists.txt:43 (install_project_dependencies):
  Unknown CMake command  install_project_dependencies .

-- Configuring incomplete, errors occurred!
See also ***/kandinsky/build1/CMakeFiles/CMakeOutput.log.`

Do you have any idea why i am getting this?

**Comment by lgpasquale** [comment]
I just tried to compile kandinsky under mint 18.1 and couldn't replicate the same error, so I'll need your help.

CMake is trying to download [cupid](https://github.com/lgpasquale/cupid) (which is just a bunch of cmake scripts I wrote). This is done in the first lines of kandinsky's CMakeLists.txt:
```cmake
        message(STATUS "Downloading cupid...")
        file(DOWNLOAD https://github.com/lgpasquale/cupid/archive/${CUPID_VERSION}.zip
            "${CMAKE_BINARY_DIR}/cupid.zip")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf cupid.zip
            WORKING_DIRECTORY "${CMAKE_BINARY_DIR}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E rename "cupid-${CUPID_VERSION}" "cupid"
            WORKING_DIRECTORY "${CMAKE_BINARY_DIR}")
```
It happens in three steps:
- first it tries to download a specific version of cupid from github
- then it extracts the archive
- finally it renames the extracted folder from `cupid-aff23ed14632c33ab6e60bb26ff686f1cc9b3838` to `cupid`.

Judging by your output, the first two commands seem to have completed without errors, while the third one complained about not being able to find the extracted directory.
Can you please tell me if you have both a file named `cupid.zip` and a directory named `cupid-aff23ed14632c33ab6e60bb26ff686f1cc9b3838` in your build directory?
This can help us understand if the first two steps did what they were supposed to do.

**Comment by rcalxrc08** [comment]
i have only a file called cupid.zip but it is an empty file,
if i clone manually the last version, or the version that you download in the cmake, everything works.

**Comment by lgpasquale** [comment]
Have you tried deleting that file (cupid.zip) and running cmake again? Maybe it was just a download gone bad...

**Comment by rcalxrc08** [comment]
Yes sure, and it didn't work

**Comment by rcalxrc08** [comment]
There was a problem with my cmake version, i don't know exactly what.
I removed that and installed the last version and everything now works.
One thing that i suggest you is to use tags instead of the number of commit in the cupid library.
It is easier to refer at "0.0.1" instead of your commit number.
Thank you again!
